Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
srun: error: cn014: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
6s_chi2.dat.lock'
srun: error: cn028: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
Tsrun: error: cn028: task 0: Exited with exit code 1
tert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhosrun: error: cn034: task 0: Exited with exit code 1
2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhoTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
ostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
srun: error: cn036: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
exit code 1
srun: error: cn058: task 0: Exited with exit code 1
srun: error: cn058: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
srun: error: cn009: task 0: Exited with exit code 1
srun: error: cn008: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
bnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
srun: error: cn007: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
srun: error: cn058: task 0: Exited with exit code 1
srun: error: cn058: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
srun: error: cn058: task 0: Exited with exit code 1
srun: error: cn058: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
srun: error: cn028: task 0: Exited with exit code 1
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'
srun: error: cn028: task 0: Exited with exit code 1
srun: error: cn028: task 0: Exited with exit code 1
srun: error: cn028: task 0: Exited with exit code 1
iBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
hostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
                                                                Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
rum.dat.lock'
 (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
srun: error: cn057: task 0: Exited with exit code 1
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", lsrun: error: cn008: task 0: Exited with exit code 1
(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
ert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
ostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
TTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
k 0: Exited with exit code 1
stert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmassrun: error: cn009: task 0: Exited with exit code 1
ted with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3pTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
niBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
srun: error: cn057: task 0: Exited with exit code 1
stert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhosrun: error: cn013: task 0: Exited with exit code 1
2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
srun: error: cn013: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
srun: error: cn012: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhosrun: error: cn012: task 0: Exited with exit code 1
stert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
t/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
srun: error: cn011: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
th exit code 1
srun: error: cn013: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
srun: error: cn044: task 0: Exited with exit code 1
iniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
it.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
srun: error: cn007: task 0: Exited with exit code 1
srun: error: cn007: task 0: Exited with exit code 1
stert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
srun: error: cn043: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhoTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
zprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
srun: error: cn044: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhoTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'

Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
srun: error: cn063: task 0: Exited with exit code 1
srun: error: cn044: task 0: Exited with exit code 1
srun: error: cn043: task 0: Exited with exit code 1
srun: error: cn043: task 0: Exited with exit code 1
srun: error: cn047: task 0: Exited with exit code 1
Traceback (most recent call last):
with exit code 1
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_evis_spectrum.dat.lock'
4_0.015_eps_0.0001/5m_13d_8h_34m_46s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_invmass_spectrum.dat.lock'
srun: error: cn047: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_13d_8h_34m_46s_csrun: error: cn047: task 0: Exited with exit code 1
h exit code 1
srun: error: cn063: task 0: Exited with exit code 1
srun: error: cn047: task 0: Exited with exit code 1
srun: error: cn063: task 0: Exited with exit code 1
