Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn030: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn030: task 0: Exited with exit code 1
srun: error: cn030: task 0: Exited with exit code 1
stert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn027: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_chi2.dat.lock'
srun: error: cn042: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn019: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn019: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn042: task 0: Exited with exit code 1
srun: error: cn042: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhosrun: error: cn068: task 0: Exited with exit code 1
98, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn016: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn068: task 0: Exited with exit code 1
srun: error: cn068: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn046: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_chi2.dat.lock'
srun: error: cn065: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn040: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn040: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
srun: error: cn040: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_costheta_spectrum.dat.lockceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_chi2.dat.lock'
srun: error: cn037: task 0: Exited with exit code 1
srun: error: cn037: task 0: Exited with exit code 1
srun: error: cn037: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_chi2.dat.lock'
srun: error: cn037: task 0: Exited with exit code 1
srun: error: cn037: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn037: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn038: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0001/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn038: task 0: Exited with exit code 1
srun: error: cn038: task 0: Exited with exit code 1
