Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
srun: error: cn039: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn039: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
srun: error: cn064: task 0: Exited with exit code 1
srun: error: cn064: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn020: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
srun: error: cn020: task 0: Exited with exit code 1
srun: error: cn020: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
ck'
srun: error: cn020: task 0: Exited with exit code 1
srun: error: cn020: task 0: Exited with exit code 1
srun: error: cn068: task 0: Exited with exit code 1
srun: error: cn068: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn065: task 0: Exited with exit code 1
srun: error: cn065: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn040: task 0: Exited with exit code 1
srun: error: cn040: task 0: Exited with exit code 1
srun: error: cn040: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn046: task 0: Exited with exit code 1
srun: error: cn046: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
 error: cn037: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
osrun: error: cn059: task 0: Exited with exit code 1
/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn031: task 0: Exited with exit code 1
srun: error: cn031: task 0: Exited with exit code 1
srun: error: cn031: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhoTraceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.sainiBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn037: task 0: Exited with exit code 1
srun: error: cn037: task 0: Exited with exit code 1
              Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                srun: error: cn037: task 0: Exited with exit code 1
                                                    Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
                                   File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
srun: error: cn037: task 0: Exited with exit code 1
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn037: task 0: Exited with exit code 1
srun: error: cn037: task 0: Exited with exit code 1
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn030: task 0: Exited with exit code 1
stert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
srun: error: cn037: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
back (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn043: task 0: Exited with exit code 1
inglefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
srun: error: cn038: task 0: Exited with exit code 1
srun: error: cn038: task 0: Exited with exit code 1
srun: error: cn038: task 0: Exited with exit code 1
srun: error: cn038: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
srun: error: cn038: task 0: Exited with exit code 1
inglefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_costheta_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lTraceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn063: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
ock'
srun: error: cn043: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn043: task 0: Exited with exit code 1
srun: error: cn063: task 0: Exited with exit code 1
srun: error: cn063: task 0: Exited with exit code 1
srun: error: cn038: task 0: Exited with exit code 1
srun: error: cn063: task 0: Exited with exit code 1
srun: error: cn063: task 0: Exited with exit code 1
srun: error: cn043: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
srun: error: cn027: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_enu_spectrum.dat.lock'
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_evis_spectrum.dat.lock'
srun: error: cn011: task 0: Exited with exit code 1
srun: error: cn011: task 0: Exited with exit code 1
srun: error: cn011: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_delta_mz_1.25_eps_0.01/5m_10d_19h_24m_55s_invmass_spectrum.dat.lock'
srun: error: cn019: task 0: Exited with exit code 1
srun: error: cn019: task 0: Exited with exit code 1
